### ISSUE TITLE
causative/conflicting

### ISSUE THREAD

**Issue by glnegri** [PathwayAndDataAnalysis/causalpath#10]
Hi,
causalpath.jar generates two sif files, causative and conflicting. I can't find anything in the documentation about the conflicting path and the differences between the two. 
Thanks

**Comment by ozgunbabur** [comment]
Hi glnegri,

There is a wiki page for the description of output files. It is linked from the GitHub project main page. Please look for the sentence "You can also find [a description of output files here](https://github.com/PathwayAndDataAnalysis/causalpath/blob/master/wiki/OutputFiles.md)."

On that page, the conflicting network is defined as below.

**conflicting.sif:** In addition to the causal result network, CausalPath generates a network showing the causal priors with contradicting experiment data. Here contradicting means that the data change is significant within the thresholds, but the change direction is opposite to what we expect by the causal priors.

**conflicting.format:** This file complements conflicting.sif by providing visual features of the network.
