### ISSUE TITLE
Multiple phosphosite intensity values per phosphoprotein

### ISSUE THREAD

**Issue by patriciaB96** [PathwayAndDataAnalysis/causalpath#14]
Hi, 

I have a phosphoproteomic dataset in which each identified phosphosite has an individual intensity value. 

So for example: ITGB4_pS1511 -> Intensity 1
                        ITGB4_pS1517 -> Intensity 2
                        ITGB4_pS1451 -> Intensity 3

How do I deal with this in regard to the required input format where every row should contain one protein with all its identified phosphosites, but only one intensity value?

Thanks in regard, 
Patricia

**Comment by ozgunbabur** [comment]
Hi Patricia,

CausalPath format does not require rows having a protein with all detected phosphosites. On the contrary, in your case, each row is supposed to be a detected phosphopeptide. A protein will typically have multiple rows. If that phosphopeptide has multiple phosphorylated locations, then this should be indicated on that row.

Please see the wiki page below to understand the format.
https://github.com/PathwayAndDataAnalysis/causalpath/blob/master/wiki/InputFormat.md

The provided example on that page may also be useful.

Best,
Ozgun

**Comment by cannin** [comment]
@patriciaB96 Something like this: 

```
ITGB4_pS1511  ITGB4  S1511  A  -0.0012
ITGB4_pS1517  ITGB4  S1517     -4.6e-5
```

**Comment by patriciaB96** [comment]
Great, thank you - that helped me a lot! The analysis finally worked now :)

Best, Patricia
