### ISSUE TITLE
Add description about "unknown-site-effects.txt"

### ISSUE THREAD

**Issue by cannin** [PathwayAndDataAnalysis/causalpath#2]
No description on site currently. Specifically, it would be good to mention whether it is expected that sites with unknown effects will appear in the resulting network; currently, I think they do and it is not clear why.

**Comment by ozgunbabur** [comment]
Please find a documentation at https://github.com/PathwayAndDataAnalysis/causalpath/blob/master/wiki/OutputFiles.md
