### ISSUE TITLE
Why are negative values in log fold change discarded

### ISSUE THREAD

**Issue by taowanwan** [PathwayAndDataAnalysis/causalpath#20]
hello,
I have extracted the phospho sites that are significant and have a log2 FC value >= 1 || <= -1. I do not know the effect of any proteins so I want to use online available databases. 

ID | Symbols | Sites | Effect | LFC
CAVIN4:Q5BKX8:355 | CAVIN4 | S355 |   | -3.606
FAM131B:Q86XD5:114 | FAM131B | S114 |   | -5.7672
ZDHHC5:Q9C0B5:425 | ZDHHC5 | S425 |   | -1.967
NIBAN2:Q96TA1:641 | NIBAN2 | S641 |   | -3.7233
ACD:Q96AP0:25 | ACD | S25 |   | -4.8168
CEP170:Q5SW79:1280 | CEP170 | S1280 |   | -4.1542
......

My parameters.txt file is as follows:
proteomics-values-file = screening.txt
id-column = ID
symbols-column = Symbols
sites-column = Sites
effect-column = Effect
value-transformation = geometric-mean
value-column = LFC
threshold-for-data-significance = 1 phosphoprotein

I can successfully run and obtain data, but none of the information with LFC <-1 appears in the result data. However, when I take the absolute value of the LFC values less than -1, the corresponding information appears in the result. It seems like the threshold is only extracting information with LFC > 1 for analysis. Is this really the case? How can I make improvements?

**Comment by ozgunbabur** [comment]
Hi taowanwan,

LFC < -1 should count as significance change when you set the threshold to 1. You can check that by adding the line 
```
show-all-genes-with-proteomic-data = true
```
to the parameters.txt file. This will display those genes with significant data on them even if they are not connected to anything on the result network. This check would tell you if the lack of results is due to not detecting significant change, or if it is due to not satisfying conditions of causality.

In any case, if you like us to take a more detailed look, please send your input files and we will have a better idea.

Best,
Ozgun

**Comment by taowanwan** [comment]
Hi Ozgun,
Thank you for your help!
I try to add the line(show-all-genes-with-proteomic-data = true) to the parameters.txt file. But there is no result. 
<img width="374" alt="image" src="https://github.com/PathwayAndDataAnalysis/causalpath/assets/156800761/16bfbd8f-a152-4504-b645-a3d7c7e53cfe">

This is my input files, could you please take a look? Thank you very much!
[input.txt](https://github.com/PathwayAndDataAnalysis/causalpath/files/14033785/input.txt)
[parameters.txt](https://github.com/PathwayAndDataAnalysis/causalpath/files/14033789/parameters.txt)

Best,
Wanwan

**Comment by ozgunbabur** [comment]
Hi Wanwan,

Thanks for the files. There was a bug in the geometric-mean option (fixed now), but also you don't need that as your values are in a single column. The better option for you is `as-is-single-value`. And you don't need to use `show-all-genes-with-proteomic-data = true` anymore. I made other changes to the [parameters.txt](https://github.com/PathwayAndDataAnalysis/causalpath/files/14055531/parameters.txt) file as well. Please download and work on this one. I set the threshold to 2 to manage the result network size. Please tune it accordingly.

I noticed that all your rows are downregulations. That looks odd. If everything is decreasing, maybe they are not actually dephosphorylations but a normalization issue. Is this the entire data or are you trying to use a subset of it? If this is a subset, I suggest using the entire dataset for having the results in full size. This is especially important if you also want to calculate network sigificances (I added this to the parameters file, but it will not work properly if this is not the entire dataset).

Let me know how it goes.
Ozgun

**Comment by taowanwan** [comment]
Hi Ozgun,

I have successfully run it. Thank you very much! 
As you mentioned, these are indeed subsets, as I am more focused on the downgraded data. I will follow your advice and attempt to analyze the entire dataset. Thank you for your sincere and prompt response!
I have another question, due to the large amount of data, if I want to focus more on the down-regulated data, how should I handle the generated results?

Best,
Wanwan

**Comment by ozgunbabur** [comment]
Hi Wanwan,

It looks like I missed your last message which was months ago. Sorry about that. I will answer it hoping it is still relevant for you.

If you want to focus on downregulations, the best way is this:
1. Detect gene symbols that have downregulated data mapped on them.
2. Make a copy of causative.sif in the results, but only keep those lines that have one (or two) of your genes. What I mean is, delete a line if that relation does not involve any gene from the previous step.
3. Each .sif file needs a .format file to properly display. To generate a .format file for the .sif file that you generated in the previous step, simply copy causative.format and rename accordingly. If your new sif file has the name "causative-subset.sif", then make the name of the format copy "causative-subset.format".

Now you can load them to causalpath.org and visuallize.
