### ISSUE TITLE
feature-column option is not working in JAR file (only in the web-server)

### ISSUE THREAD

**Issue by jtorrejon81** [PathwayAndDataAnalysis/causalpath#21]
Hello,

Many thanks for this excellent tool, I have run it with my omic data (Proteome + Phospho using foldchange as value-colum) using both web-server and locally JAR file and it is working pretty well.
However when I include RNA data and adding the option feature-column (to distinguish between Proteome, RNA and Phospho), it only works in the web server and locally I have this error:

Exception in thread "main" java.lang.RuntimeException: Unknown parameter: feature-column

Looks like than the JAR file does not recognize well the parameter feature-column

Many thanks for your help and feedback in advance
Sincerely yours,
Jacob

**Comment by ozgunbabur** [comment]
Thanks for pointing that out. We have just made a new release: v1.2.1. Please find it on the front page. This should work fine. Please let us know otherwise.
