### ISSUE TITLE
JAR file does not recognize well the parameter "as-is-single-value"

### ISSUE THREAD

**Issue by kaupuks** [PathwayAndDataAnalysis/causalpath#22]
Hello,

Looks like than the JAR file does not recognize well the parameter "as-is-single-value", it only works in the web server and locally I have this error:

C:\Users\algir>java -jar causalpath.jar PC_Control_test
Exception in thread "main" java.lang.RuntimeException: Value transformation "as-is-single-value" not recognized.

Best,
Algirdas

**Comment by ozgunbabur** [comment]
Hi, the latest jar (v1.2.1, please see the releases on the front page) should support this option. Please try and let us know if you encounter any other problems.
