### ISSUE TITLE
 hello，this URL has now been updated, Do you think there may be some issues

### ISSUE THREAD

**Issue by kunpengLiLkp** [PathwayAndDataAnalysis/causalpath#24]
![image](https://github.com/PathwayAndDataAnalysis/causalpath/assets/140494835/61a4d2d1-19ba-4536-8950-2360c8c9de52)

https://www.genenames.org/cgi-bin/download/custom?col=gd_hgnc_id&col=gd_app_sym&col=gd_prev_sym%22%20+%20%22&col=gd_aliases&col=gd_pub_chrom_map&col=family.name&col=md_prot_id&status=Approved&status_opt=2&where=&%22%20+%20%22order_by=gd_app_sym_sort&format=text&limit=&hgnc_dbtag=on&submit=submit

**Comment by ozgunbabur** [comment]
Hi kunpengLiLkp,

Thanks for the debug. We have updated the URL. Please update the project and try again. 

This resource is not directly in the causalpath project, but in another project that causalpath uses. Sometimes it takes time for maven to realize that other project is updated. If it doesn't work instantly, try a bit later.
