### ISSUE TITLE
java.lang.RuntimeException: Cannot find the current PC All.hgnc.txt.gz

### ISSUE THREAD

**Issue by andriy-nikolov** [PathwayAndDataAnalysis/causalpath#26]
Hi, thanks for developing the tool!

Running the example from "sample-data-and-parameters" now fails with an exception:

> Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Cannot find the current PC All.hgnc.txt.gz file in https://www.pathwaycommons.org/archives/PC2/v12/

It probably concerns more the "resource" project, as it seems that the path may have changed (possibly, to http://download.baderlab.org/PathwayCommons/PC2/v12/PathwayCommons12.All.hgnc.txt.gz  ?)

**Comment by ozgunbabur** [comment]
Hi Andriy,

That was due to an accidental commit. It should be fixed in the latest code and the latest release. Can you please update and try again?

Thanks,
Ozgun

**Comment by andriy-nikolov** [comment]
Hi Ozgun, 

Indeed, works now, after a refresh. Thanks a lot!

Best,
Andriy
