### ISSUE TITLE
v1.2.1 gives error on UniProt download

### ISSUE THREAD

**Issue by hasanbalci** [PathwayAndDataAnalysis/causalpath#27]
I tried to apply the protocol on [this site](https://star-protocols.cell.com/protocols/1199) with causalpath v1.2.1 and when I run "java -jar causalpath.jar gpvi_mass_spec" it says "Cannot download ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz" and throws an exception. However, after that if I replaced the jar file with v1.2.0 then it worked. On the other hand, if I directly try with v1.2.0, it also doesn't work because of the issue mentioned [here](https://github.com/PathwayAndDataAnalysis/causalpath/issues/23). I tried it with macOS operating system and Java 8. 

Probably, first running v1.2.1 correctly sets the problematic URL in v1.2.0 but it crashes in another URL. But then running v1.2.0 works because of the problematic URL is correctly set by v1.2.1. But I'm not sure how healthy it is to run like this.

Maybe using https instead of ftp can solve the problem.

**Comment by ozgunbabur** [comment]
Hi Hasan,
I just tried it on Ubuntu with openjdk 11.0.24 and it worked fine. 

But also I tracked to see why it is downloading this from UniProt, and found that this is due to a faulty design of some new features. I fixed that in v1.2.1. Please download and try again.

**Comment by hasanbalci** [comment]
Hi Özgün, thanks for your reply. I downloaded v1.2.1 and tried again and it worked fine this time.
