### ISSUE TITLE
Compilation error RhoGEF symbol missing

### ISSUE THREAD

**Issue by cannin** [PathwayAndDataAnalysis/causalpath#4]
[ERROR] /Users/user/default/workspace/causalpath/src/main/java/org/panda/causalpath/resource/NetworkLoader.java:[71,74] cannot find symbol
  symbol:   variable RhoGEF
  location: class org.panda.causalpath.resource.NetworkLoader

**Comment by ozgunbabur** [comment]
I believe I fixed that already. It was due to a disharmony between this project and the "resource" project.
